version: '3.8'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - npm_cache:/app/.npm-cache
    networks:
      - app-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/kitchen-shop
      - JWT_SECRET=your_jwt_secret
      - PORT=5003
    volumes:
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  npm_cache:
  backend_node_modules:
  mongodb_data: 