# version: '3.8'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      # - VITE_API_URL=http://localhost:5003
    depends_on:
      - backend
    networks:
      - shopperz-network

  backend:
    container_name: backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/kitchen-shop
      - JWT_SECRET=your_jwt_secret
      - PORT=5003
      # - CORS_ORIGIN=http://frontend:8080
    depends_on:
      - mongodb
    networks:
      - shopperz-network

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shopperz-network

networks:
  shopperz-network:
    driver: bridge    
    name: shopperz-network

volumes:
  mongodb_data:
    name: shopperz-mongodb-data
